# Generated by Django 4.0.1 on 2022-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Артикул')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('amaunt', models.IntegerField(verbose_name='Количество')),
            ],
        ),
    ]
